---
version: '3'
services:

# START SERVICE journalbeat.sasl
  journalbeat:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.journalbeat.sasl:7.8.0
    environment: ['ES_JOURNALBEAT_FILEPATHS=${INGEST_JOURNAL_SASL_ENVIRONMENT_FILEPATHS}','ES_JOURNALBEAT_SEEK=${INGEST_JOURNAL_SASL_ENVIRONMENT_SEEK}','ES_JOURNALBEAT_INCLUDE_MATCHES=${INGEST_JOURNAL_SASL_ENVIRONMENT_INCLUDE_MATCHES}','ES_JOURNALBEAT_OUTPUT_CONSOLE=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONSOLE}','ES_JOURNALBEAT_OUTPUT_ELASTICSEARCH=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_ELASTICSEARCH}','ES_JOURNALBEAT_OUTPUT_LOGSTASH=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_LOGSTASH}','ES_JOURNALBEAT_OUTPUT_KAFKA=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_KAFKA}','ES_JOURNALBEAT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS}','ES_JOURNALBEAT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX}','ES_JOURNALBEAT_OUTPUT_CONFIG_ELASTICSEARCH_SSL=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_SSL}','ES_JOURNALBEAT_OUTPUT_CONFIG_ELASTICSEARCH_USERNAME=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_USERNAME}','ES_JOURNALBEAT_OUTPUT_CONFIG_ELASTICSEARCH_PASSWORD=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_PASSWORD}','ES_JOURNALBEAT_OUTPUT_CONFIG_LOGSTASH_HOSTS=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_LOGSTASH_HOSTS}','ES_JOURNALBEAT_OUTPUT_CONFIG_LOGSTASH_INDEX=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_LOGSTASH_INDEX}','ES_JOURNALBEAT_OUTPUT_CONFIG_KIBANA_HOST=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_HOST}','ES_JOURNALBEAT_OUTPUT_CONFIG_KIBANA_DASHBOARDS=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_DASHBOARDS}','ES_JOURNALBEAT_OUTPUT_CONFIG_KAFKA_HOSTS=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_HOSTS}','ES_JOURNALBEAT_OUTPUT_CONFIG_KAFKA_SSL=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_SSL}','ES_JOURNALBEAT_OUTPUT_CONFIG_KAFKA_USERNAME=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_USERNAME}','ES_JOURNALBEAT_OUTPUT_CONFIG_KAFKA_PASSWORD=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_PASSWORD}','ES_JOURNALBEAT_OUTPUT_CONFIG_KAFKA_TOPIC=${INGEST_JOURNAL_SASL_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_TOPIC}']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_journalbeat_volume:/usr/share/journalbeat/data','/etc:/hostfs/etc:ro'${INGEST_JOURNAL_SASL_ENVIRONMENT_FILEPATHS_MAPPING}]
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${INGEST_JOURNAL_SASL_DEPLOY_MODE}
      resources:
        limits:
          memory: '${INGEST_JOURNAL_SASL_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${INGEST_JOURNAL_SASL_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${INGEST_JOURNAL_SASL_COMPOSE_EXTENSIONS}
# END SERVICE journalbeat.sasl

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_journalbeat_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
